# https://taskfile.dev

version: "3"
tasks:
  test:
    cmds:
      - go test ./mylog/ ./project ./sandbox/ ./clock/ ./pkg/  {{.CLI_ARGS}}
    sources:
      - pkg/**/*.go
      - project/**/*.go
      - testutils/**/*.go
    silent: true
