# https://taskfile.dev

version: "3"
tasks:
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
    sources:
      - ./**/*.go
    silent: true
  release:
    cmds:
      - echo "Running tests..."
      - go test ./...
      - git-cliff --output CHANGELOG.md --tag $(git-cliff --bumped-version)
      - git add CHANGELOG.md
      - 'git commit -m "docs(release): update changelog for $(git-cliff --bumped-version)"'
      - git tag $(git-cliff --bumped-version)
      - git push origin HEAD --tags
      - echo "Release process complete"
