# https://taskfile.dev

version: "3"
tasks:
  test:
    cmds:
      - go test ./project ./testutils/ ./pkg/
    sources:
      - pkg/**/*.go
      - project/**/*.go
      - testutils/**/*.go
    silent: true
